import { currentUser } from "../src";
import { mainWrapper } from "./addNewComment";
import { selectDeleteBtns } from "./selectBtns";

export const addNewReply = (item) => {
  const replyDiv = document.createElement("div");
  replyDiv.className = "reply-comment";
  mainWrapper.append(replyDiv);
  const replyLikes = document.createElement("div");
  replyLikes.className = "reply-likes";
  replyDiv.append(replyLikes);
  const replyplusSign = document.createElement("span");
  replyplusSign.className = "reply-plus";
  replyplusSign.innerText = "+";
  replyLikes.append(replyplusSign);
  const replylikesCounter = document.createElement("span");
  replylikesCounter.className = "reply-count-likes";
  replylikesCounter.innerText = `${item.score}`;
  replyLikes.append(replylikesCounter);
  const replyminusSign = document.createElement("span");
  replyminusSign.className = "reply-minus";
  replyminusSign.innerText = "-";
  replyLikes.append(replyminusSign);
  const replycommentsRightSide = document.createElement("div");
  replycommentsRightSide.className = "reply-comment-right";
  replyDiv.append(replycommentsRightSide);
  const replycommentsHeader = document.createElement("div");
  replycommentsHeader.className = "reply-comment-name-date-reply";
  replycommentsRightSide.append(replycommentsHeader);
  const replycommentsHeadersLeftSide = document.createElement("div");
  replycommentsHeadersLeftSide.className = "reply-comment-up-left";
  replycommentsHeader.append(replycommentsHeadersLeftSide);
  const replyuserImage = document.createElement("img");
  replyuserImage.setAttribute("src", `${item.user.image.png}`);
  replyuserImage.setAttribute("alt", "img");
  replycommentsHeadersLeftSide.append(replyuserImage);
  const replycommentAuthor = document.createElement("h3");
  replycommentAuthor.className = "reply-author";
  replycommentAuthor.innerText = `${item.user.username}`;
  replycommentsHeadersLeftSide.append(replycommentAuthor);
  const replycommentDate = document.createElement("date");
  replycommentDate.className = "reply-comment-date";
  replycommentDate.innerText = `${item.createdAt}`;
  replycommentsHeadersLeftSide.append(replycommentDate);
  const replyreplyLogo = document.createElement("div");
  replyreplyLogo.className = "reply-reply-logo";
  replycommentsHeader.append(replyreplyLogo);
  const replyreplyImg = document.createElement("img");
  replyreplyImg.setAttribute("src", "./images/icon-reply.svg");
  replyreplyImg.setAttribute("alt", "img");
  replyreplyLogo.append(replyreplyImg);
  const replyreplySpan = document.createElement("span");
  replyreplySpan.innerText = "Reply";
  replyreplyLogo.append(replyreplySpan);
  const replycommentText = document.createElement("p");
  replycommentText.className = "reply-comment-text";
  replycommentText.innerText = `${item.content}`;
  replycommentsRightSide.append(replycommentText);
  if (item.user.username == currentUser.username) {
    const replyDeleteButtonLogo = document.createElement("img");
    replyDeleteButtonLogo.setAttribute("src", "./images/icon-delete.svg");
    replyDeleteButtonLogo.setAttribute("alt", "delete-btn");
    replyDeleteButtonLogo.className = "delete";
    replyreplyLogo.append(replyDeleteButtonLogo);
    const replyDeleteSpan = document.createElement("span");
    replyDeleteSpan.innerText = "Delete";
    replyDeleteSpan.className = "delete";
    replyreplyLogo.append(replyDeleteSpan);
    const replyEditButton = document.createElement("img");
    replyEditButton.setAttribute("src", "./images/icon-edit.svg");
    replyEditButton.setAttribute("alt", "editimage");
    replyreplyLogo.append(replyEditButton);
    const replyEditSpan = document.createElement("span");
    replyEditSpan.innerText = "Edit";
    replyEditSpan.className = "replyeditspan";
    replyreplyLogo.append(replyEditSpan);
    replyreplyImg.remove();
    replyreplySpan.remove();
  }
  selectDeleteBtns();
};
