import { currentUser } from "../src";

export const mainWrapper = document.querySelector(".main-wrapper");
export const addNewCommentByCurrentUser = (element) => {
  const commentDiv = document.createElement("div");
  commentDiv.className = "comment";
  const likesDiv = document.createElement("div");
  likesDiv.className = "likes";
  commentDiv.append(likesDiv);
  const plusSign = document.createElement("span");
  plusSign.className = "plus";
  plusSign.innerText = "+";
  likesDiv.append(plusSign);
  const likesCounter = document.createElement("span");
  likesCounter.className = "count-likes";
  likesCounter.innerText = `${element.score}`;
  likesDiv.append(likesCounter);
  const minusSign = document.createElement("span");
  minusSign.className = "minus";
  minusSign.innerText = "-";
  likesDiv.append(minusSign);
  const commentsRightSide = document.createElement("div");
  commentsRightSide.className = "comment-right";
  commentDiv.append(commentsRightSide);
  const commentsHeader = document.createElement("div");
  commentsHeader.className = "comment-name-date-reply";
  commentsRightSide.append(commentsHeader);
  const commentsHeadersLeftSide = document.createElement("div");
  commentsHeadersLeftSide.className = "comment-up-left";
  commentsHeader.append(commentsHeadersLeftSide);
  const userImage = document.createElement("img");
  userImage.setAttribute("src", `${element.user.image.png}`);
  userImage.setAttribute("alt", "img");
  commentsHeadersLeftSide.append(userImage);
  const commentAuthor = document.createElement("h3");
  commentAuthor.className = "author";
  commentAuthor.innerText = `${element.user.username}`;
  commentsHeadersLeftSide.append(commentAuthor);
  const commentDate = document.createElement("date");
  commentDate.className = "comment-date";
  commentDate.innerText = `${element.createdAt}`;
  commentsHeadersLeftSide.append(commentDate);
  const replyLogo = document.createElement("div");
  replyLogo.className = "reply-logo";
  commentsHeader.append(replyLogo);
  const replyImg = document.createElement("img");
  replyImg.setAttribute("src", "./images/icon-reply.svg");
  replyImg.setAttribute("alt", "img");
  replyLogo.append(replyImg);
  // console.log(element.user.username);
  // console.log(currentUser.username);
  const replySpan = document.createElement("span");
  replySpan.innerText = "Reply";
  replyLogo.append(replySpan);
  const commentText = document.createElement("p");
  commentText.className = "comment-text";
  commentText.innerText = `${element.content}`;
  commentsRightSide.append(commentText);
  if (element.user.username == currentUser.username) {
    const replyDeleteButtonLogo = document.createElement("img");
    replyDeleteButtonLogo.setAttribute("src", "./images/icon-delete.svg");
    replyDeleteButtonLogo.setAttribute("alt", "delete-btn");
    replyLogo.append(replyDeleteButtonLogo);
    const replyDeleteSpan = document.createElement("span");
    replyDeleteSpan.innerText = "Delete";
    replyDeleteSpan.className = "replydeletespan";
    replyLogo.append(replyDeleteSpan);
    const replyEditButton = document.createElement("img");
    replyEditButton.setAttribute("src", "./images/icon-edit.svg");
    replyEditButton.setAttribute("alt", "editimage");
    replyLogo.append(replyEditButton);
    const replyEditSpan = document.createElement("span");
    replyEditSpan.innerText = "Edit";
    replyEditSpan.className = "replyeditspan";
    replyLogo.append(replyEditSpan);
    replyImg.remove();
    replySpan.remove();
  }
  mainWrapper.append(commentDiv);
};
